php:
  preset: laravel
  risky: true
  finder:
    exclude:
      - modules
      - frontend
      - node_modules
      - storage
      - vendor
    name: "*.php"
    not-name: "*.blade.php"
js:
  tab-width: 4
  use-tabs: false
  print-width: 120
  double-quotes: false
  trailing-commas: es5
  semicolons: true
  arrow-parens: avoid
  bracket-spacing: true
  finder:
    exclude:
      - node_modules
      - backend
    name:
      - "*.js"
      - "*.jsx"
    not-name:
      - "*.min.js"
ts: false
css: false
py: false