services:
  backend:
    build:
      path: ./backend
      manifest: compose/prod/php-fpm/Dockerfile
    port: 5000
    health: /admin/login
    internal: false
    environment:
      - "*"

  frontend:
    build:
      path: ./frontend
      manifest: compose/prod/frontend/Dockerfile
    port: 3000
    health: /
    internal: false
    environment:
      - "*"

  nginx:
    build:
      path: ./backend
      manifest: compose/prod/nginx/Dockerfile
    port: 80
    domain: ${HOST}
    health: /vw-status
    links:
      - backend
      - frontend
