version: '3'

volumes:
  local_mysql_data: {}
  local_mysql_data_backups: {}
  local_es_data: {}

services:

  ###
  # DBs, Caches, ETC Services
  ###
  mysql:
    build: ./compose/local/mysql
    volumes:
      - local_mysql_data:/var/lib/mysql
      - local_mysql_data_backups:/backups
    ports:
    - 3306:3306
    environment:
      - MYSQL_DATABASE=delivermyride
      - MYSQL_USER=delivermyride
      - MYSQL_PASSWORD=delivermyride
      - MYSQL_ROOT_PASSWORD=delivermyride

  redis:
    image: redis:latest


  ###
  # ES Stuff
  ###
  elasticsearch:
    build:
      context: ./compose/local/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - local_es_data:/usr/share/elasticsearch/data:delegated
      - ./compose/local/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build:
      context: ./compose/local/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/local/kibana/config/:/usr/share/kibana/config:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  ###
  # Dev things
  ###
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"

  ###
  # Actual Application
  ###
  app:
    build: ./compose/local/php-fpm
    ports:
        - "9000:9000"
    volumes:
      - .:/app
    links:
        - mysql
        - elasticsearch
        - redis
        
  nginx:
    build: ./compose/local/nginx
    ports:
        - "5000:80"
    links:
        - app
        - mysql
    volumes:
      - .:/app
      - ./logs/nginx/:/var/log/nginx:cached
