export default [
    {
        title: 'Acura',
        logo: '/static/images/makes/acura.jpg',
        query: ['make:Acura'],
        featured: false,
    },
    {
        title: 'Alfa Romeo',
        logo: '/static/images/makes/alfa-romeo.png',
        query: ['make:Alfa Romeo'],
        featured: false,
    },
    {
        title: 'Audi',
        logo: '/static/images/makes/audi.jpg',
        query: ['make:Audi'],
        featured: false,
    },
    {
        title: 'BMW',
        logo: '/static/images/makes/bmw.jpg',
        query: ['make:BMW'],
        featured: true,
    },
    {
        title: 'Buick',
        logo: '/static/images/makes/buick.jpg',
        query: ['make:Buick'],
        featured: true,
    },
    {
        title: 'Cadillac',
        logo: '/static/images/makes/cadillac.jpg',
        query: ['make:Cadillac'],
        featured: true,
    },
    {
        title: 'Chevrolet',
        logo: '/static/images/makes/chevrolet.jpg',
        query: ['make:Chevrolet'],
        featured: true,
    },
    {
        title: 'Chrysler',
        logo: '/static/images/makes/chrysler.jpg',
        query: ['make:Chrysler'],
        featured: true,
    },
    {
        title: 'Dodge',
        logo: '/static/images/makes/dodge.jpg',
        query: ['make:Dodge'],
        featured: true,
    },
    {
        title: 'Fiat',
        logo: '/static/images/makes/fiat.jpg',
        query: ['make:Fiat'],
        featured: false,
    },
    {
        title: 'Ford',
        logo: '/static/images/makes/ford.jpg',
        query: ['make:Ford'],
        featured: true,
    },
    {
        title: 'Genesis',
        logo: '/static/images/makes/genesis.png',
        query: ['make:Genesis'],
        featured: false,
    },
    {
        title: 'GMC',
        logo: '/static/images/makes/gmc.jpg',
        query: ['make:GMC'],
        featured: true,
    },
    {
        title: 'Honda',
        logo: '/static/images/makes/honda.jpg',
        query: ['make:Honda'],
        featured: false,
    },
    {
        title: 'Hyundai',
        logo: '/static/images/makes/hyundai.jpg',
        query: ['make:Hyundai'],
        featured: false,
    },
    {
        title: 'INFINITI',
        logo: '/static/images/makes/infiniti.jpg',
        query: ['make:INFINITI'],
        featured: false,
    },
    {
        title: 'Jaguar',
        logo: '/static/images/makes/jaguar.jpg',
        query: ['make:Jaguar'],
        featured: false,
    },
    {
        title: 'Jeep',
        logo: '/static/images/makes/jeep.jpg',
        query: ['make:Jeep'],
        featured: true,
    },
    {
        title: 'Land Rover',
        logo: '/static/images/makes/land-rover.png',
        query: ['make:Land Rover'],
        featured: false,
    },
    {
        title: 'Lexus',
        logo: '/static/images/makes/lexus.jpg',
        query: ['make:Lexus'],
        featured: true,
    },
    {
        title: 'Lincoln',
        logo: '/static/images/makes/lincoln.jpg',
        query: ['make:Lincoln'],
        featured: true,
    },
    {
        title: 'Mazda',
        logo: '/static/images/makes/mazda.jpg',
        query: ['make:Mazda'],
        featured: false,
    },
    {
        title: 'Mercedes-Benz',
        logo: '/static/images/makes/mercedes-benz.jpg',
        query: ['make:Mercedes-Benz'],
        featured: true,
    },
    /*
    {
        title: 'Mini',
        logo: '/static/images/makes/mini.jpg',
        query: ['make:Mini'],
        featured: false,
    },
    */
    {
        title: 'Mitsubishi',
        logo: '/static/images/makes/mitsubishi.jpg',
        query: ['make:Mitsubishi'],
        featured: false,
    },
    {
        title: 'Nissan',
        logo: '/static/images/makes/nissan.jpg',
        query: ['make:Nissan'],
        featured: false,
    },
    {
        title: 'Porsche',
        logo: '/static/images/makes/porsche.jpg',
        query: ['make:Porsche'],
        featured: false,
    },
    {
        title: 'Ram',
        logo: '/static/images/makes/ram.png',
        query: ['make:Ram'],
        featured: false,
    },
    {
        title: 'Subaru',
        logo: '/static/images/makes/subaru.jpg',
        query: ['make:Subaru'],
        featured: false,
    },
    {
        title: 'Toyota',
        logo: '/static/images/makes/toyota.jpg',
        query: ['make:Toyota'],
        featured: false,
    },
    {
        title: 'Volkswagen',
        logo: '/static/images/makes/volkswagon.jpg',
        query: ['make:Volkswagen'],
        featured: false,
    },
    {
        title: 'Volvo',
        logo: '/static/images/makes/volvo.jpg',
        query: ['make:Volvo'],
        featured: false,
    },
];
