version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers-legacy

      - image: circleci/mysql:5.7

        environment:
        - MYSQL_DATABASE=delivermyridetesting
        - MYSQL_USER=delivermyride
        - MYSQL_PASSWORD=delivermyride

      - image: redis:latest

    working_directory: ~/app

    steps:
      - checkout
      ##################################################################
      # Frontend
      ##################################################################

      # Packages
      ##################
      - restore_cache:
          keys:
            - node-v1-{{ checksum "frontend/yarn.lock" }}
            - node-v1-
      - run: cd frontend && yarn install
      - save_cache:
          key: node-v1-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules

      # Build
      ##################
      - run:
          name: Build frontend assets
          command: cd frontend && yarn build


      # Tests
      ##################
      - run:
          name: Run Frontend linting
          command: cd frontend && yarn lint

      - run:
          name: Run Frontend tests
          command: cd frontend && yarn test

      ##################################################################
      # Backend
      ##################################################################

      # Install system dependencies
      ##################
      - run:
          name: Install system packages
          command: sudo apt install -y zlib1g-dev libpng-dev
      - run:
          name: Install PHP extensions
          command: sudo -E docker-php-ext-install pdo_mysql zip
      - run:
          name: Update composer
          command: sudo composer self-update

      # Composer
      ##################
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "backend/composer.lock" }}
            - composer-v1-
      - run: cd backend && composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor

      # Application Setup
      ##################

      #- run:
      #    name: Migrate database
      #    command:  php artisan migrate --env=testing --force

      # Tests
      ##################
      - run:
          name: Run PHPunit Unit Tests
          command:  cd backend && vendor/bin/phpunit --testsuite unit

      - run:
          name: Run PHPunit Unit Feature
          command:  cd backend && vendor/bin/phpunit --testsuite feature
