version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers

      - image: circleci/mysql:5.7

        environment:
        - MYSQL_DATABASE=delivermyridetesting
        - MYSQL_USER=dmr
        - MYSQL_PASSWORD=dmr

      - image: redis:latest

    working_directory: ~/app

    steps:
      - checkout

      ##################################################################
      # Install Things
      ##################################################################
      - run:
          name: Install system packages
          command: sudo apt install -y zlib1g-dev libpng-dev
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql zip
      - run:
          name: Update composer
          command: sudo composer self-update

      ##################################################################
      # Composer
      ##################################################################
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "backend/composer.lock" }}
            - composer-v1-
      - run: cd backend && composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor

      ##################################################################
      # NPM
      ##################################################################
      - restore_cache:
          keys:
            - node-v1-{{ checksum "frontend/package.json" }}
            - node-v1-
      - run: cd frontend && yarn install
      - save_cache:
          key: node-v1-{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules


      ##################################################################
      # Application Setup
      ##################################################################
      - run:
          name: Build frontend assets
          command: cd frontend && yarn build

      #- run:
      #    name: Migrate database
      #    command:  php artisan migrate --env=testing --force

      ##################################################################
      # Tests
      ##################################################################
      #- run:
      #    name: Run PHPunit tests
      #    command:  vendor/bin/phpunit

      - run:
          name: Run Javascript tests
          command: cd frontend && yarn test