#!/usr/bin/env bash


### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) mysql backup

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "Backing up the '${MYSQL_DATABASE}' database..."

export DB_USERNAME="${MYSQL_USER}"
export DB_PASSWORD="${MYSQL_PASSWORD}"
export DB_DATABASE="${MYSQL_DATABASE}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
mysqldump --user=${DB_USERNAME} --password=${DB_PASSWORD} ${DB_DATABASE} | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"
message_success "'${DB_DATABASE}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
